[package]
name = "rust_crate_flume_01"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
flume = "0.11"
futures = "0.3"
rand = "0.8"