[package]
name = "rust_26_macro_1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { version = "0.4" }
simple_logger = { version = "4.3" }
base64 = "0.21"